name             'workstation'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version          '0.1.15'

depends          'homebrew'
depends          'simple_iptables'
depends          'dmg'
depends          'macapps'
depends          'iterm2'
depends          'nginx'
depends          'varnish'
