name             'workstation'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version          '0.1.4'

depends			 'homebrew'
depends          'iptables-ng'
